name: Deploy backend

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: make push/heroku
      working-directory: backend
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: make push/heroku
